import React from 'react';
import { render, screen } from '@testing-library/react';
import RootLayout, { metadata } from '../layout';

// Mock Toaster component
jest.mock('@/components/ui/toaster', () => ({
  Toaster: () => <div data-testid="toaster" />,
}));

// Mock ErrorBoundary
jest.mock('@/components/error-boundary', () => ({
  ErrorBoundary: ({ children }: any) => <div data-testid="error-boundary">{children}</div>,
}));

// Mock fonts
jest.mock('next/font/google', () => ({
  Geist: () => ({
    variable: '--font-geist-sans',
  }),
  Geist_Mono: () => ({
    variable: '--font-geist-mono',
  }),
}));

describe('RootLayout', () => {
  describe('Metadata', () => {
    it('should export metadata with correct title', () => {
      expect(metadata).toBeDefined();
      expect(metadata.title).toBe('Create Next App');
    });

    it('should export metadata with correct description', () => {
      expect(metadata).toBeDefined();
      expect(metadata.description).toBe('Generated by create next app');
    });

    it('should have metadata as an object', () => {
      expect(typeof metadata).toBe('object');
    });
  });

  describe('Rendering', () => {
    it('should render without crashing', () => {
      render(
        <RootLayout>
          <div>Test Child</div>
        </RootLayout>
      );
      expect(screen.getByText('Test Child')).toBeInTheDocument();
    });

    it('should render children', () => {
      render(
        <RootLayout>
          <div data-testid="test-child">Test Content</div>
        </RootLayout>
      );
      expect(screen.getByTestId('test-child')).toBeInTheDocument();
      expect(screen.getByText('Test Content')).toBeInTheDocument();
    });

    it('should render ErrorBoundary', () => {
      render(
        <RootLayout>
          <div>Test</div>
        </RootLayout>
      );
      expect(screen.getByTestId('error-boundary')).toBeInTheDocument();
    });

    it('should render Toaster', () => {
      render(
        <RootLayout>
          <div>Test</div>
        </RootLayout>
      );
      expect(screen.getByTestId('toaster')).toBeInTheDocument();
    });
  });



  describe('Children Wrapping', () => {
    it('should wrap children in ErrorBoundary', () => {
      render(
        <RootLayout>
          <div data-testid="wrapped-child">Child Content</div>
        </RootLayout>
      );
      
      const errorBoundary = screen.getByTestId('error-boundary');
      const child = screen.getByTestId('wrapped-child');
      expect(errorBoundary).toContainElement(child);
    });

    it('should render multiple children', () => {
      render(
        <RootLayout>
          <div data-testid="child1">Child 1</div>
          <div data-testid="child2">Child 2</div>
        </RootLayout>
      );
      
      expect(screen.getByTestId('child1')).toBeInTheDocument();
      expect(screen.getByTestId('child2')).toBeInTheDocument();
    });

    it('should render complex children structures', () => {
      render(
        <RootLayout>
          <div>
            <header data-testid="header">Header</header>
            <main data-testid="main">Main Content</main>
            <footer data-testid="footer">Footer</footer>
          </div>
        </RootLayout>
      );
      
      expect(screen.getByTestId('header')).toBeInTheDocument();
      expect(screen.getByTestId('main')).toBeInTheDocument();
      expect(screen.getByTestId('footer')).toBeInTheDocument();
    });
  });



  describe('Existence Tests', () => {
    it('should be defined', () => {
      expect(RootLayout).toBeDefined();
    });

    it('should be a function', () => {
      expect(typeof RootLayout).toBe('function');
    });

    it('should export metadata', () => {
      expect(metadata).toBeDefined();
    });
  });
});
